In [1]:
import pandas as pd
import seaborn as sn

df = pd.read_csv('employees.csv')

In [2]:
df.head()

  First Name  Gender  Salary Bonus % Senior Management             Team
0    Douglas    Male   97308   6.945              TRUE        Marketing
1     Thomas    Male   61933     NaN              TRUE              NaN
2      Maria  Female  130590  11.858             FALSE          Finance
3      Jerry    Male     NaN    9.34              TRUE          Finance
4      Larry    Male  101004   1.389              TRUE  Client Services

In [3]:
df.shape

(1000, 6)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         931 non-null    str
 1   Gender             852 non-null    str
 2   Salary             998 non-null    str
 3   Bonus %            997 non-null    str
 4   Senior Management  932 non-null    str
 5   Team               957 non-null    str
dtypes: str(6)
memory usage: 81.7 KB

In [5]:
#fix the wrong data types, salary and bonus shouldn't be objects/strings
#malformed data, also deal with missing data
#we need to find the one that is least damaging to the dataset
#we have to observe and pick the best statistical technique to use

df.isnull().sum()
#shows where the null values are

First Name            69
Gender               148
Salary                 2
Bonus %                3
Senior Management     68
Team                  43
dtype: int64

In [6]:
df["Team"].unique()
#shows the unqie values for the column team

<ArrowStringArray>
[           'Marketing',                    nan,              'Finance',
      'Client Services',                'Legal',              'Product',
          'Engineering', 'Business Development',      'Human Resources',
                'Sales',                   'na',         'Distribution',
                 'n.a.',                    '?']
Length: 14, dtype: str

In [7]:
#if theres missing data python will replace with nan
#the na , n.a and ? is values that someone wrote in
#the best thing to do is get rid of the na, n.a and ?

df["Senior Management"].unique()
##again we can see contains n.a and ?

<ArrowStringArray>
['TRUE', 'FALSE', nan, 'n.a.', '?']
Length: 5, dtype: str

In [8]:
print(df["Salary"].unique())
#because its truncated them all we can expand it by using the print command

<ArrowStringArray>
[ '97308',  '61933', '130590',      nan, '101004', '115163',  '65476',
  '45906', '139852',  '63241',
 ...
 '100765', '134505', '112769',  '56450',  '98874', '132483',  '42392',
  '96914',  '60500', '129949']
Length: 994, dtype: str

In [9]:
##in all of these different cases where n.a or nan or ? or whatever
#We are gonna use those values by ignoring them to become missing values
#mdl = missing data list
#in other cases it will be other values, this list is for this perticular df
mdl = ["n.a.", "?", "NA", "n/a", "na" , "--"]
# as the data is being read in, the values from our list will be ignored
df = pd.read_csv("employees.csv", na_values = mdl)
#we created a list with the wrong inputs but in by the user

In [10]:
df.isnull().sum()
#we can see the number of missing values has increased

First Name            70
Gender               149
Salary                 5
Bonus %                4
Senior Management     71
Team                  48
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         930 non-null    str
 1   Gender             851 non-null    str
 2   Salary             995 non-null    float64
 3   Bonus %            996 non-null    float64
 4   Senior Management  929 non-null    object
 5   Team               952 non-null    str
dtypes: float64(2), object(1), str(3)
memory usage: 66.7+ KB

In [12]:
#now we have a dataset with aload of missing data
#in 3 ways we can deal with it

#1 drop the missing values:
#take a look at the statistical values before we do that 
df.describe()

              Salary     Bonus %
count     995.000000  996.000000
mean    90522.329648   10.215586
std     32880.654889    5.532077
min     35013.000000    1.015000
25%     62412.500000    5.429500
50%     90370.000000    9.850000
75%    118582.000000   14.841250
max    149908.000000   19.944000

In [13]:
new_df = df.dropna(axis=0)
# getting rid of the rows that have na
#axis = 0 means rows

new_df.isnull().sum()
#we have no missing values

First Name           0
Gender               0
Salary               0
Bonus %              0
Senior Management    0
Team                 0
dtype: int64

In [14]:
new_df.shape

(742, 6)

In [15]:
#weve lost observations
new_df.describe()

              Salary     Bonus %
count     742.000000  742.000000
mean    90318.974394   10.168340
std     32829.261501    5.591998
min     35013.000000    1.015000
25%     62023.250000    5.221750
50%     90398.500000    9.702000
75%    118041.500000   14.936000
max    149908.000000   19.944000

In [16]:
#we can see the values have changed because we dropped rows

#2 flagging:
#We can put in 0 to show there is missing data, in categorical features like gender, we may decide to wrote unknown

new_df = df
new_df.shape

(1000, 6)

In [17]:
new_df["Salary"] = new_df["Salary"].fillna(0)
#we filled the na with 0

In [18]:
new_df["Salary"].head()

0     97308.0
1     61933.0
2    130590.0
3         0.0
4    101004.0
Name: Salary, dtype: float64

In [19]:
#we must check how that changed the statistical nature of the data 
new_df["Salary"].describe()

count      1000.000000
mean      90069.718000
std       33414.574342
min           0.000000
25%       61982.500000
50%       90020.500000
75%      118384.500000
max      149908.000000
Name: Salary, dtype: float64

In [20]:
#fill 0 is the most away from the original values
#we can flag categorical data too
new_df["Gender"]=new_df["Gender"].fillna("Unknown")
new_df["Gender"].head(10)

0       Male
1       Male
2     Female
3       Male
4       Male
5    Unknown
6     Female
7     Female
8    Unknown
9     Female
Name: Gender, dtype: str

In [21]:
#3 imputation means to put values in somewhere
#in stats of something is normally disprutated, the mean mode and whatever are the same
#never ever use the mean value full stop, the median is a better representation.
#fill with the median, or backfill take value of behind and use that or foward fill use the value after it
new_df = df

In [22]:
#forward fill
                                    #here
new_df["Salary"]= new_df["Salary"].ffill()

In [23]:
new_df["Salary"].head(10)

0     97308.0
1     61933.0
2    130590.0
3         0.0
4    101004.0
5    115163.0
6     65476.0
7     45906.0
8         0.0
9    139852.0
Name: Salary, dtype: float64

In [24]:
new_df.describe()

              Salary     Bonus %
count    1000.000000  996.000000
mean    90069.718000   10.215586
std     33414.574342    5.532077
min         0.000000    1.015000
25%     61982.500000    5.429500
50%     90020.500000    9.850000
75%    118384.500000   14.841250
max    149908.000000   19.944000

In [25]:
#backfill
new_df["Salary"]= new_df["Salary"].bfill()
new_df.describe()

              Salary     Bonus %
count    1000.000000  996.000000
mean    90069.718000   10.215586
std     33414.574342    5.532077
min         0.000000    1.015000
25%     61982.500000    5.429500
50%     90020.500000    9.850000
75%    118384.500000   14.841250
max    149908.000000   19.944000

In [29]:
#interpolate
new_df["Salary"] = new_df["Salary"].interpolate(method="linear", direction="forward")
new_df.describe()

              Salary     Bonus %
count    1000.000000  996.000000
mean    90069.718000   10.215586
std     33414.574342    5.532077
min         0.000000    1.015000
25%     61982.500000    5.429500
50%     90020.500000    9.850000
75%    118384.500000   14.841250
max    149908.000000   19.944000

In [27]:
#interpolate causes the leats amount of damage in this dataset
#the next dataset the bfill or ffill or dropping is the best
#you wont know until you experiment